#!/usr/bin/env bash
# Install nginx web server

# Update package index and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create an HTML file that prints "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Add redirect configuration to Nginx using sed
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=laBqRHKS27w;/" /etc/nginx/sites-available/default

# Test Nginx configuration
sudo nginx -t

# Restart Nginx server to apply changes
sudo service nginx restart

# Enable Nginx to start on boot
sudo service nginx enable

# Exit on success status
exit 0
