#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Use sed to add redirection configuration
sudo sed -i '/^[^#]*location \/ {/a \\tlocation = \/redirect_me {\n\t\treturn 301 https:\/\/meet.google.com;\n\t}' /etc/nginx/sites-available/default

# Use sed to add custom 404 page configuration
sudo sed -i '/^[^#]*location \/ {/a \\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Use sed to add custom header to Nginx configuration
HOSTNAME=$(hostname)
string_block="        add_header X-Served-By $HOSTNAME;\n"
sudo sed -i "/^[^#]*location \/ {/a $string_block" /etc/nginx/sites-available/default

# Test Nginx configuration
sudo nginx -t

# Restart Nginx server to apply changes
sudo service nginx restart
