#!/usr/bin/env bash
# Script to install and configure HAproxy on lb-01 server

# Install HAproxy
sudo apt-get update
sudo apt-get install haproxy -y

# Enable HAproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

echo "
frontend http_front
	bind *:80
	default_backend http_back

backend http_back
	balance roundrobin
	server 250117-web-01 52.91.149.94:80 check
	server 250117-web-02 52.91.178.191:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAproxy
sudo service haproxy restart
