#!/usr/bin/env bash
# This script displays:
# The content of the current directory
# in a list format
# where only the part of the name after the first dash is displayed
for file in *; do
    if [[ ! "$file" =~ ^\. ]]; then
	echo "$file" | awk -F- '{print $2}'
    fi
done
